application: cloud-mania
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css
  mime_type: "text/css"

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /(connect|oauth)
  script: main.app
  secure: always

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest
